# This is meant for convenience of testing/running Docker in development
version: '3.1'
services:
  bot:
    build: .
    image: joebullard/slack-translate-bot
    env_file: ./.env
    environment:
      GOOGLE_TRANSLATE_SERVICE_ACCOUNT_JSON: /tmp/service-account.json
    volumes:
      - ./credentials/service-account.json:/tmp/service-account.json
